version: '3'
services:
  event-log:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/go/src/github.com/tobyjsullivan/event-log
    ports:
    - "3003:3000"
    depends_on:
    - "db"
    - "event-store"
    environment:
    - EVENT_STORE_API=http://event-store:3000/
    - PG_HOSTNAME=db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  db:
    image: tobyjsullivan/logs-db:1.0.0
    environment:
    - POSTGRES_PASSWORD=pass1234
    volumes:
    - ./data:/var/lib/postgresql/data
  event-store:
    image: tobyjsullivan/event-store:3.0.0
    env_file:
    - ./env/event-store.env
  event-reader:
    image: tobyjsullivan/event-reader:3.0.0
    env_file:
    - ./env/event-reader.env

