version: '3'
services:
  event-log:
    build: .
    ports:
    - "3003:3000"
    depends_on:
    - "postgres"
    - "event-store"
    environment:
    - PG_HOSTNAME=postgres
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  flyway:
    image: tobyjsullivan/flyway:latest
    volumes:
    - ./db:/sql
    depends_on:
    - "postgres"
  postgres:
    image: postgres:9.6.3
    environment:
    - POSTGRES_PASSWORD=pass1234
    volumes:
    - ./data:/var/lib/postgresql/data
  event-store:
    image: tobyjsullivan/event-store.v3
    ports:
    - "3001:3000"
    env_file:
    - ./env/event-store.env
  event-reader:
    image: tobyjsullivan/event-reader.v3
    ports:
    - "3002:3000"
    env_file:
    - ./env/event-reader.env

